appweb/urls.py
from django.urls import path 
from django.conf.urls import url

from . import views 

app_name = 'appweb'

urlpatterns = [
    url(r'^detail/(?P<detail_id>[0-9]+)$', views.detail, name='detail'),
    url(r'^update/(?P<update_id>[0-9]+)$', views.update, name='update'),
    url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),

]

cobaweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('appweb.urls', namespace="appweb")),
]

appweb/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    nama        = models.CharField(max_length=50)
    dosen       = models.CharField(max_length=100)
    sks         = models.PositiveIntegerField()
    semester    = models.CharField(max_length=6, choices= [('Ganjil', 'Ganjil'),('Genap', 'Genap'),],default= 'Ganjil')
    tahun       = models.CharField(max_length=9,
        choices= [
    ('2020/2021', '2020/2021'),
    ('2021/2022', '2021/2022'),
    ('2022/2023', '2022/2023'),
    ],default='2019/2020')
    ruang        = models.CharField(max_length=20)
    deskripsi    = models.CharField(max_length=300)

    def __str__(self):
        return self.name

appweb/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['nama', 'dosen', 'sks', 'semester', 'tahun', 'ruang', 'deskripsi']
        widgets = {
            'nama'      : forms.TextInput(attrs={'class': 'form-control'}),
            'dosen'     : forms.TextInput(attrs={'class': 'form-control'}),
            'sks'       : forms.NumberInput(attrs={'class': 'form-control'}),
            'semester'  : forms.Select(attrs={'class': 'form-control'}),
            'tahun'     : forms.Select(attrs={'class': 'form-control'}),
            'ruang'     : forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.Textarea(attrs={'class': 'form-control'}),
        }

appweb/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.
from datetime import datetime
from .models import Course
from .forms import CourseForm

# Views ini terinspirasi dari Tugas Kelompok saya

def create(request):
    matkul_form = CourseForm()
    if request.method == "POST":
        matkul_form = CourseForm(request.POST)
        if matkul_form.is_valid():
            matkul_form.save()
            return redirect('appweb:list')
      
    context = {
        'matkul_form'   : matkul_form,
        'title'         : "Tambah Matkul"
        }
    return render(request, 'appweb/matkul_create.html', context)

def update(request,update_id):
	matkul_update = Course.objects.get(id=update_id)
	
	data_matkul = {
		'nama'	    : matkul_update.nama,
		'dosen'	    : matkul_update.dosen,
		'sks'	    : matkul_update.sks,
        'semester'  : matkul_update.semester,
        'tahun'     : matkul_update.tahun,
        'ruang'     : matkul_update.ruang,
        'deskripsi' : matkul_update.deskripsi,
	}
	matkul_form = CourseForm(request.POST or None, initial=data_matkul, instance=matkul_update)

	if request.method == 'POST':
		if matkul_form.is_valid():
			matkul_form.save()

		return redirect('appweb:list')

	context = {
		"title":"Update Matkul",
		"matkul_form":matkul_form,
	}

	return render(request,'appweb/matkul_update.html',context)


def list(request):
    all_matkul = Course.objects.all()

    context = {
        'title' : 'List Matkul',
        'all_matkul' : all_matkul
    }
    return render(request, 'appweb/matkul_list.html', context)


def delete(request, delete_id):
    Course.objects.filter(id=delete_id).delete()
    return redirect('appweb:list')


def detail(request, detail_id):
    matkul_detail = Course.objects.get(id=detail_id)

    context = {
        "title" : "Detail Matkul",
        "matkul_detail": matkul_detail,
    }
    return render(request, "appweb/matkul_detail.html", context)

appweb/templates/appweb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<head>
    {% block css %}

    {% endblock css %}    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>   
        <title>
            {% block page_title %}

            {% endblock page_title %}
        </title>


       

        <!-----CSS BOOTSTRAP----->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="../../static/appweb/css/index.css">

    </head>

    <body class="home mt-5">
        {% include './navbar.html' %}
        {% block content %}

        {% endblock content %}
        {% include './footer.html' %}
    </body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>

appweb/templates/appweb/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'appweb/css/index.css' %}">

<!--CONTACT-->
<footer class="text-white" id="contact">
  <div class="container mt-5">
    <div class="row">
      <div class="col text-">
        <h3><b>Ardelia Yasmin Yolandaya</b></h3>
      </div>
    </div>
  </div>
</footer>
</section>

<footer class="text-white">
<div class="container">
  <div class="row">
    <div class="col text-center">
      <p>Copyright &COPY; 2021</p>
    </div>
  </div>
</div>
</footer>

appweb/templates/appweb/matkul_create.html
{% extends 'appweb/base.html' %}
{% load static %}

{% block page_title %}
    {{title}}
{% endblock page_title %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'appweb/css/index.css' %}">

{% block content %}

<div class="container" style="margin-top: 120px;margin-bottom:30px; min-height:100vh;">
    <form method="POST">
        {% csrf_token %}
            <div class="form-group">
              <label>Nama Mata Kuliah</label>
              {{matkul_form.nama}}
            </div>
  
            <div class="form-group">
              <label for="dosen">Dosen Pengajar</label>
              {{matkul_form.dosen}}
            </div>
  
              <div class="form-group">
              <label for="sks">Jumlah SKS</label>
              {{matkul_form.sks}}
            </div>
  
            <div class="form-group">
              <label for="semester">Semester</label>
              {{matkul_form.semester}}
            </div>
  
            <div class="form-group">
              <label for="tahunAjar">Tahun Ajar</label>
              {{matkul_form.tahun}}
            </div>
  
            <div class="form-group">
              <label for="ruang">Ruang</label>
              {{matkul_form.ruang}}
            </div>
  
          <div class="form-group">
              <label for="deskripsi">Deskripsi</label>
              {{matkul_form.deskripsi}}
          </div>
          <button type="submit" class="btn btn-primary">Tambah Matkul</button>
        </form>
</div>
{% endblock content %}

appweb/templates/appweb/matkul_detail.html
{% extends 'appweb/base.html' %}
{% load static %}

<html>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block page_title %}
        {{title}}
    {% endblock page_title %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/appweb/css/index.css">

    {% block content %}
    <div class="container text-center" style="min-height: 80vh; margin-top:210px">
        <div class="card-body">
            <h2>Detail Matkul {{matkul_detail.nama}}</h2>
            <h5>Nama Dosen : {{matkul_detail.dosen}}</h5>
            <h5>Banyak SKS : {{matkul_detail.sks}}</h5>
            <h5>Semeseter : {{matkul_detail.semester}}</h5>
            <h5>Tahun Ajaran : {{matkul_detail.tahun}}</h5>
            <h5>Ruang Kelas : {{matkul_detail.ruang}}</h5>
            <h5>Deskripsi Singkat : {{matkul_detail.deskripsi}}</h5>
          </div>
        
    </div>
       
    {% endblock content %}

appweb/templates/appweb/matkul_list.html
{% extends 'appweb/base.html' %}
{% load static %}

{% block page_title %}
    {{title}}
{% endblock page_title %}

{% block content %}
<div class="container" style="margin-top :120px; min-height:100vh">
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Nama Matkul</th>
            <th scope="col">Nama Dosen</th>
            <th scope="col">Banyak SKS</th>
            <th scope="col">Delete</th>
            <th scope="col">Update</th>
            <th scope="col">Detail</th>
          </tr>
        </thead>

        <tbody>
        {% for matkul in all_matkul %}
        <tr>
            <th scope="row">{{forloop.counter}}</th> <!--kalo mau mulai dari 0, pake {{forloop.counter0}}-->
              <td>{{matkul.nama}}</td>
              <td>{{matkul.dosen}}</td>
              <td>{{matkul.sks}}</td>
            <td><a class="btn btn-outline-danger" href="{% url 'appweb:delete' matkul.id %}">Delete</a></td>
            <td><a class="btn btn-outline-success" href="{% url 'appweb:update' matkul.id %}" title="">Update</a>
            <td><a class="btn btn-outline-primary" href="{% url 'appweb:detail' matkul.id %}" title="">Detail</a>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <a class="btn btn-primary" href="{% url 'appweb:create' %}">Tambah</a>
</div>

{% endblock content %}

appweb/templates/appweb/matkul_update.html
{% extends 'appweb/base.html' %}
{% load static %}

{% block page_title %}
    {{title}}
{% endblock page_title %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'appweb/css/index.css' %}">

{% block content %}
    <div class="container" style="margin-top:120px; margin-bottom:30px; min-height:100vh;">
        <form method="POST">
            {% csrf_token %}
                <div class="form-group">
                  <label>Nama Mata Kuliah</label>
                  {{matkul_form.nama}}
                </div>
      
                <div class="form-group">
                  <label for="dosen">Dosen Pengajar</label>
                  {{matkul_form.dosen}}
                </div>
      
                  <div class="form-group">
                  <label for="sks">Jumlah SKS</label>
                  {{matkul_form.sks}}
                </div>
      
                <div class="form-group">
                  <label for="semester">Semester</label>
                  {{matkul_form.semester}}
                </div>
      
                <div class="form-group">
                  <label for="tahunAjar">Tahun Ajar</label>
                  {{matkul_form.tahun}}
                </div>
      
                <div class="form-group">
                  <label for="ruang">Ruang</label>
                  {{matkul_form.ruang}}
                </div>
      
              <div class="form-group">
                  <label for="deskripsi">Deskripsi</label>
                  {{matkul_form.deskripsi}}
              </div>
              <button type="submit" class="btn btn-primary">Update Matkul</button>
            </form>
    </div>
{% endblock content %}

appweb/templates/appweb/navbar.html
<link rel="stylesheet" href="../../static/appweb/css/index.css">

 <!--NAVBAR-->
 <div class="main">
  <nav class="navbar fixed-top navbar-expand-lg">
    <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'appweb:list' %}">MATA KULIAH</a>
        </li>
        </li>
      </ul>
    </div>
  </nav>
</div>
</div>